# Generated by Django 2.2.6 on 2020-01-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180927_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publication',
            field=models.ManyToManyField(blank=True, to='projects.Publication'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=200, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmid',
            field=models.CharField(blank=True, max_length=200, verbose_name='PMID'),
        ),
    ]
